# .readthedocs.yml
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"


python:
  install:
    - method: editable  # pip install -e .
      path: .
    - requirements: docs/requirements.txt


sphinx:
  configuration: docs/source/conf.py
  builder: html


sphinx:
  fail_on_warning: true
